// Build step for bundled models. Run manually when adding one:
//   node bake-models.js
// Parses each OBJ exactly as the app does, normalises it the same way, then
// quantises to int16 so the shipped file is a fraction of the OBJ's size and
// needs no parsing at load.
const fs = require('fs');

const SOURCES = {
  susan:    'S:/Blender Filer/Susan.obj',
  discoman: 'S:/Blender Filer/Discoman.obj',
  danceman: 'S:/Blender Filer/danceman.obj',
  blocks:   'S:/Blender Filer/Audiovismodels.obj'
};

function objToTris(text) {
  const verts = [], tris = [];
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (line.startsWith('v ')) { const p = line.split(/\s+/); verts.push([+p[1], +p[2], +p[3]]); }
    else if (line.startsWith('f ')) {
      const idx = line.split(/\s+/).slice(1).map(tok => {
        const i = parseInt(tok.split('/')[0], 10);
        return i < 0 ? verts.length + i : i - 1;
      });
      for (let k = 1; k + 1 < idx.length; k++) {
        const a = verts[idx[0]], b = verts[idx[k]], c = verts[idx[k + 1]];
        if (a && b && c) tris.push(a, b, c);
      }
    }
  }
  return tris;
}

const out = {};
for (const [key, path] of Object.entries(SOURCES)) {
  const tris = objToTris(fs.readFileSync(path, 'utf8'));
  let miX=1e9,miY=1e9,miZ=1e9,maX=-1e9,maY=-1e9,maZ=-1e9;
  for (const v of tris) {
    if(v[0]<miX)miX=v[0]; if(v[0]>maX)maX=v[0];
    if(v[1]<miY)miY=v[1]; if(v[1]>maY)maY=v[1];
    if(v[2]<miZ)miZ=v[2]; if(v[2]>maZ)maZ=v[2];
  }
  const cx=(miX+maX)/2, cy=(miY+maY)/2, cz=(miZ+maZ)/2;
  const sc = 2.1 / (Math.max(maX-miX, maY-miY, maZ-miZ) || 1);
  const pos = new Float32Array(tris.length * 3);
  for (let i = 0; i < tris.length; i++) {
    pos[i*3]   = (tris[i][0]-cx)*sc;
    pos[i*3+1] = (tris[i][1]-cy)*sc;
    pos[i*3+2] = (tris[i][2]-cz)*sc;
  }
  let span = 0; for (const v of pos) span = Math.max(span, Math.abs(v));
  const q = Buffer.alloc(pos.length * 2);
  for (let i = 0; i < pos.length; i++) q.writeInt16LE(Math.round(pos[i]/span*32767), i*2);
  let err = 0;
  for (let i = 0; i < pos.length; i++) err = Math.max(err, Math.abs(q.readInt16LE(i*2)/32767*span - pos[i]));
  out[key] = { span, data: q.toString('base64'), tris: tris.length/3, err };
  console.log(`${key}: ${tris.length/3} triangles, max error ${err.toExponential(2)}`);
}

const body = Object.entries(out)
  .map(([k, v]) => `  ${k}: { span: ${v.span.toFixed(8)}, data: "${v.data}" }`)
  .join(',\n');
fs.writeFileSync('models.js',
`// Bundled models — positions only, triangulated and normalised at build time,
// quantised to int16 and base64'd. Generated by bake-models.js; do not edit.
${Object.entries(out).map(([k,v])=>`// ${k}: ${v.tris} triangles`).join('\n')}
window.BUNDLED_MODELS = {
${body}
};
`);
console.log('models.js:', (fs.statSync('models.js').size/1024).toFixed(1) + 'KB');
